#!/usr/bin/env bash
# setup-macos.sh — one-command dev setup for macOS contributors.
#
# Checks each prerequisite and offers to install what's missing. Nothing is
# installed without asking (pass --yes to accept every offer). Two paths:
#   Nix present  → point at `nix develop` (the recommended, CI-tested shell)
#   no Nix       → rustup + Homebrew deps for a bare `cargo build`
#
# See CONTRIBUTING.md for the full onboarding guide.
set -uo pipefail

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "setup-macos.sh is for macOS. On Linux: install Nix, then 'nix develop'." >&2
  exit 1
fi

yes_all=0
case "${1:-}" in
--yes | -y) yes_all=1 ;;
-h | --help)
  echo "usage: ./setup-macos.sh [--yes]"
  exit 0
  ;;
"") ;;
*)
  echo "unknown argument: $1 (usage: ./setup-macos.sh [--yes])" >&2
  exit 1
  ;;
esac

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$here" || exit 1

ok() { printf '  \033[32mok\033[0m    %s\n' "$1"; }
miss() { printf '  \033[33mMISS\033[0m  %s\n' "$1"; }
step() { printf '\n\033[1m%s\033[0m\n' "$1"; }

# ask "<question>" → 0 if the user (or --yes) accepts.
ask() {
  if ((yes_all)); then
    echo "  $1 — yes (--yes)"
    return 0
  fi
  local reply
  read -r -p "  $1 [y/N] " reply
  [[ $reply == [yY]* ]]
}

step "thegn macOS setup"

# ── Xcode Command Line Tools (compiler + git; needed on every path) ─────────
if xcode-select -p >/dev/null 2>&1; then
  ok "Xcode Command Line Tools"
else
  miss "Xcode Command Line Tools (compiler + git)"
  if ask "run 'xcode-select --install' now?"; then
    xcode-select --install || true
    echo "  Finish the installer dialog, then re-run ./setup-macos.sh"
    exit 0
  fi
  echo "  Cannot build without a compiler; aborting." >&2
  exit 1
fi

# ── Path 1: Nix (recommended) ────────────────────────────────────────────────
if command -v nix >/dev/null 2>&1; then
  ok "Nix — using the recommended dev-shell path"
  if command -v direnv >/dev/null 2>&1 && [[ -f .envrc ]]; then
    if ask "enable direnv for this repo (auto-enters the dev shell)?"; then
      direnv allow
    fi
  fi
  step "Next steps"
  cat <<'EOF'
  nix develop          # toolchain + all dev tools (first run downloads a lot)
  just build           # debug build
  just start name=dev  # run the compositor with isolated state
EOF
  exit 0
fi

miss "Nix (recommended — pinned toolchain, all dev tools, CI parity)"
echo "  Install: https://install.determinate.systems (then re-run this script)"
if ! ask "continue WITHOUT Nix (rustup + Homebrew)?"; then
  exit 0
fi

# ── Path 2: bare macOS (rustup + Homebrew) ───────────────────────────────────
step "Bare-macOS prerequisites"

if command -v cargo >/dev/null 2>&1; then
  ok "rust toolchain ($(rustc --version 2>/dev/null || echo cargo))"
else
  miss "rust toolchain (stable ≥ 1.89)"
  if ask "install rustup (official installer, no sudo)?"; then
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
    # shellcheck disable=SC1091 # generated by rustup above
    [[ -f "$HOME/.cargo/env" ]] && . "$HOME/.cargo/env"
  else
    echo "  Cannot build without cargo; aborting." >&2
    exit 1
  fi
fi

if command -v brew >/dev/null 2>&1; then
  ok "Homebrew"
  for pkg in pkg-config just; do
    if command -v "$pkg" >/dev/null 2>&1; then
      ok "$pkg"
    else
      miss "$pkg"
      if ask "brew install $pkg?"; then brew install "$pkg"; fi
    fi
  done
  # Optional runtime tools thegn shells out to when present.
  optional=(gh lazygit fzf gum git-delta yazi)
  wanted=()
  for pkg in "${optional[@]}"; do
    bin="$pkg"
    [[ $pkg == git-delta ]] && bin="delta"
    command -v "$bin" >/dev/null 2>&1 || wanted+=("$pkg")
  done
  if ((${#wanted[@]})); then
    if ask "install optional tools (${wanted[*]}) — PR panels, lazygit, file drawer?"; then
      brew install "${wanted[@]}"
    fi
  else
    ok "optional tools (gh lazygit fzf gum delta yazi)"
  fi
else
  miss "Homebrew — install pkg-config + just yourself, or get brew: https://brew.sh"
fi

# ── Build ─────────────────────────────────────────────────────────────────────
step "Build"
if ask "build now and install tg / tg-tui / thegn to ~/.local/bin (./install.sh)?"; then
  ./install.sh
else
  cat <<'EOF'
  Dev loop (no install):
    cargo build --workspace     # or: just build
    just start name=dev         # run the compositor with isolated state
  When you want real binaries on PATH later: ./install.sh
EOF
fi

step "Done — see CONTRIBUTING.md for the dev loop and macOS notes."
