//! Durable lifecycle notes for PTY crash diagnosis. These records are never
//! loaded as signal targets; a stale pid is diagnostic data only.

use std::path::PathBuf;

fn path(daemon: &str, session: &str) -> PathBuf {
    thegn_core::util::xdg_state_home()
        .join("thegn/pty-shutdown")
        .join(format!("{daemon}-{session}.json"))
}

pub(crate) fn record(
    daemon: &str,
    session: &str,
    pid: Option<u32>,
    phase: &str,
    result: Option<&str>,
) {
    // Both identifiers are generated by this daemon (hex daemon id and
    // session id), and this data is never consumed as process authority.
    let value = serde_json::json!({
        "daemon_generation": daemon,
        "session_id": session,
        "pid": pid,
        "phase": phase,
        "shutdown_result": result,
        "updated_at_ms": super::now_ms(),
    });
    crate::platform::write_state_file(
        &path(daemon, session),
        &serde_json::to_string(&value).unwrap_or_default(),
    );
}
