//! End-to-end behaviour of the merge-guard hook under a pre-commit framework.
//!
//! The unit tests in `merge_guard` prove *where* the script lands. This proves
//! the thing that actually broke: that the script still **fires** from the
//! `pre-merge-commit.legacy` position a framework shim execs — blocking a
//! sandboxed merge, allowing a host-side one, and leaving the framework's own
//! checks running either way.
//!
//! The shim here is a stand-in for prek/pre-commit, mirroring the one behaviour
//! that matters: run `<hook>.legacy` and propagate its exit status. That keeps
//! the test hermetic (no prek on PATH, so it runs anywhere `git` does) — the
//! real prek was verified by hand against this same arrangement.
//!
//! Unix-only as a whole: the shim is a `#!/bin/sh` script installed with an
//! executable mode bit, which is not a thing on Windows. Every test here was
//! already `#[cfg(unix)]`, but the helpers were not — so on Windows the file
//! still tried to compile a `repo_with_shim` that calls a `#[cfg(unix)]`
//! `write_exec`, and `cargo check --all-targets` failed. Gating the crate
//! keeps the helpers and their imports out of the Windows build too.
#![cfg(unix)]

use std::path::Path;

use thegn_core::merge_guard::{self, InstallAction, Placement};

/// A framework shim: announces itself, then delegates to `.legacy` exactly as
/// prek does, propagating a refusal.
const FAKE_SHIM: &str = r#"#!/bin/sh
# File generated by prek: https://github.com/j178/prek
hook_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
echo "FRAMEWORK_RAN" >&2
legacy="$hook_dir/pre-merge-commit.legacy"
if [ -x "$legacy" ]; then
  "$legacy" "$@" || exit $?
fi
exit 0
"#;

/// A framework shim invoked from somewhere that is *not* its installed slot.
/// Real prek detects migration mode and fails — which is precisely what an
/// orphan parked at `.thegn-orig` does to every merge in the checkout.
const MIGRATION_MODE_SHIM: &str = r#"#!/bin/sh
# File generated by prek: https://github.com/j178/prek
echo "error: prek's Git shim is installed in migration mode" >&2
exit 2
"#;

struct Out {
    ok: bool,
    stderr: String,
}

/// Run git in `dir`. Routed through `util::git_cmd` (the repo invariant the lint
/// guardrail enforces), which gives `git -C dir` with the GIT_DIR-family env
/// scrubbed — needed here because the suite may itself run inside a git hook.
///
/// Signing is forced off and identity supplied: these fixtures inherit the
/// developer's global config, where `commit.gpgsign = true` would hang every
/// commit on a pinentry the test runner has no terminal for.
fn git_env(dir: &Path, envs: &[(&str, &str)], args: &[&str]) -> Out {
    let mut c = thegn_core::util::git_cmd(dir);
    c.args(["-c", "commit.gpgsign=false", "-c", "tag.gpgsign=false"])
        .args(args)
        .env("GIT_AUTHOR_NAME", "t")
        .env("GIT_AUTHOR_EMAIL", "t@e")
        .env("GIT_COMMITTER_NAME", "t")
        .env("GIT_COMMITTER_EMAIL", "t@e")
        // The guard keys off these; default them off so a developer running the
        // suite from inside a live thegn sandbox doesn't get a spurious refusal.
        .env_remove("THEGN_SANDBOX")
        .env_remove("THEGN_MERGE_GUARD_OFF");
    for (k, v) in envs {
        c.env(k, v);
    }
    let out = c.output().expect("git must be on PATH");
    Out {
        ok: out.status.success(),
        stderr: String::from_utf8_lossy(&out.stderr).to_string(),
    }
}

fn git(dir: &Path, args: &[&str]) -> Out {
    git_env(dir, &[], args)
}

fn must(dir: &Path, args: &[&str]) {
    let o = git(dir, args);
    assert!(o.ok, "git {args:?} failed: {}", o.stderr);
}

fn scratch(tag: &str) -> std::path::PathBuf {
    let d = std::env::temp_dir().join(format!(
        "tg-mgh-{tag}-{}-{:x}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .subsec_nanos()
    ));
    let _ = std::fs::remove_dir_all(&d);
    std::fs::create_dir_all(&d).unwrap();
    d
}

#[cfg(unix)]
fn write_exec(path: &Path, body: &str) {
    use std::os::unix::fs::PermissionsExt;
    std::fs::write(path, body).unwrap();
    let mut p = std::fs::metadata(path).unwrap().permissions();
    p.set_mode(0o755);
    std::fs::set_permissions(path, p).unwrap();
}

/// A repo with one commit on `main` and a `side` branch that merges cleanly,
/// plus the framework shim installed in the `pre-merge-commit` slot.
fn repo_with_shim(tag: &str) -> std::path::PathBuf {
    let dir = scratch(tag);
    must(&dir, &["init", "-q", "-b", "main"]);
    std::fs::write(dir.join("base.txt"), "base\n").unwrap();
    must(&dir, &["add", "-A"]);
    must(&dir, &["commit", "-q", "-m", "base"]);

    must(&dir, &["checkout", "-q", "-b", "side"]);
    std::fs::write(dir.join("side.txt"), "side\n").unwrap();
    must(&dir, &["add", "-A"]);
    must(&dir, &["commit", "-q", "-m", "side"]);

    must(&dir, &["checkout", "-q", "main"]);
    std::fs::write(dir.join("main.txt"), "main\n").unwrap();
    must(&dir, &["add", "-A"]);
    must(&dir, &["commit", "-q", "-m", "mainward"]);

    write_exec(
        &dir.join(".git/hooks").join(merge_guard::HOOK_NAME),
        FAKE_SHIM,
    );
    dir
}

#[cfg(unix)]
#[test]
fn guard_refuses_a_sandboxed_merge_from_the_legacy_position() {
    let dir = repo_with_shim("refuse");
    let hooks = dir.join(".git/hooks");

    let plan = merge_guard::install(&hooks).unwrap();
    assert_eq!(plan.placement, Placement::Legacy, "shim must keep the slot");
    assert_eq!(plan.action, InstallAction::Wrote);

    // A merge from inside a sandbox, in the primary worktree: refused — and by
    // OUR message, reached through the framework's shim.
    let o = git_env(
        &dir,
        &[("THEGN_SANDBOX", "1")],
        &["merge", "--no-ff", "side"],
    );
    assert!(!o.ok, "the guard must refuse: {}", o.stderr);
    assert!(
        o.stderr
            .contains("refusing to merge in the canonical checkout"),
        "expected the guard's refusal, got: {}",
        o.stderr
    );
    // The framework still ran — we did not silence it to get here.
    assert!(o.stderr.contains("FRAMEWORK_RAN"), "stderr: {}", o.stderr);
    let _ = std::fs::remove_dir_all(&dir);
}

#[cfg(unix)]
#[test]
fn guard_allows_a_host_merge_and_still_runs_the_framework() {
    let dir = repo_with_shim("allow");
    let hooks = dir.join(".git/hooks");
    merge_guard::install(&hooks).unwrap();

    // No THEGN_SANDBOX: a host-side merge is coherent, so it proceeds — and the
    // framework's own checks still run. This is the regression that mattered:
    // the old arrangement failed *every* merge, sandboxed or not.
    let o = git(&dir, &["merge", "--no-ff", "side", "-m", "m"]);
    assert!(o.ok, "host merge must succeed: {}", o.stderr);
    assert!(o.stderr.contains("FRAMEWORK_RAN"), "stderr: {}", o.stderr);
    let _ = std::fs::remove_dir_all(&dir);
}

#[cfg(unix)]
#[test]
fn guard_allows_a_sandboxed_merge_in_a_linked_worktree() {
    // The guard is scoped to the *primary* worktree; linked worktrees are not
    // the incoherent case, and merges there must keep working under a sandbox.
    let dir = repo_with_shim("linked");
    merge_guard::install(&dir.join(".git/hooks")).unwrap();

    let wt = dir.join("wt");
    must(
        &dir,
        &["worktree", "add", "-q", wt.to_str().unwrap(), "-b", "wtbr"],
    );
    // Give the linked worktree something to merge.
    let o = git_env(
        &wt,
        &[("THEGN_SANDBOX", "1")],
        &["merge", "--no-ff", "side", "-m", "m"],
    );
    assert!(
        o.ok,
        "a linked-worktree merge must not be refused: {}",
        o.stderr
    );
    let _ = std::fs::remove_dir_all(&dir);
}

#[cfg(unix)]
#[test]
fn escape_hatch_lets_a_sandboxed_merge_through() {
    let dir = repo_with_shim("hatch");
    merge_guard::install(&dir.join(".git/hooks")).unwrap();

    let o = git_env(
        &dir,
        &[("THEGN_SANDBOX", "1"), ("THEGN_MERGE_GUARD_OFF", "1")],
        &["merge", "--no-ff", "side", "-m", "m"],
    );
    assert!(o.ok, "THEGN_MERGE_GUARD_OFF must allow: {}", o.stderr);
    let _ = std::fs::remove_dir_all(&dir);
}

#[cfg(unix)]
#[test]
fn repaired_checkout_merges_again() {
    // The exact shape the old code left behind — our hook in the slot, the
    // framework's shim parked in `.thegn-orig` where the allow path execs it.
    // Before the fix that combination failed EVERY merge; after `install`
    // repairs it, a host merge works and the framework still runs.
    let dir = repo_with_shim("repaired");
    let hooks = dir.join(".git/hooks");
    write_exec(
        &hooks.join(merge_guard::CHAINED_NAME),
        FAKE_SHIM, // the displaced shim, poisoned into the chain
    );
    write_exec(
        &hooks.join(merge_guard::HOOK_NAME),
        merge_guard::HOOK_SCRIPT,
    );

    let plan = merge_guard::install(&hooks).unwrap();
    assert!(plan.restore_shim, "the shim must get its slot back");
    assert!(
        !hooks.join(merge_guard::CHAINED_NAME).exists(),
        "the parked shim must not be left in the chain"
    );

    let o = git(&dir, &["merge", "--no-ff", "side", "-m", "m"]);
    assert!(o.ok, "merge must work after repair: {}", o.stderr);
    assert!(o.stderr.contains("FRAMEWORK_RAN"), "stderr: {}", o.stderr);

    // …and the guard still bites when it should.
    let dir2 = repo_with_shim("repaired2");
    let hooks2 = dir2.join(".git/hooks");
    write_exec(&hooks2.join(merge_guard::CHAINED_NAME), FAKE_SHIM);
    write_exec(
        &hooks2.join(merge_guard::HOOK_NAME),
        merge_guard::HOOK_SCRIPT,
    );
    merge_guard::install(&hooks2).unwrap();
    let o2 = git_env(
        &dir2,
        &[("THEGN_SANDBOX", "1")],
        &["merge", "--no-ff", "side"],
    );
    assert!(
        !o2.ok,
        "guard must still refuse after repair: {}",
        o2.stderr
    );
    assert!(
        o2.stderr.contains("refusing to merge"),
        "stderr: {}",
        o2.stderr
    );

    let _ = std::fs::remove_dir_all(&dir);
    let _ = std::fs::remove_dir_all(&dir2);
}

/// The healthy framework arrangement, then a stray `prek install` reclaims the
/// slot and orphans the shim it displaced into `.thegn-orig`. Nothing repaired
/// this: `restore_shim` only fires when *our* hook is in the slot, and here a
/// shim is — so the orphan sat there breaking every merge.
#[cfg(unix)]
fn repo_with_orphaned_shim(tag: &str) -> std::path::PathBuf {
    let dir = repo_with_shim(tag);
    let hooks = dir.join(".git/hooks");
    merge_guard::install(&hooks).unwrap();
    write_exec(&hooks.join(merge_guard::CHAINED_NAME), MIGRATION_MODE_SHIM);
    dir
}

#[cfg(unix)]
#[test]
fn hook_script_skips_an_orphaned_shim() {
    // The installer only runs when thegn starts, so between the stray install
    // and the next launch the script itself has to cope. It must refuse to exec
    // a shim from the chained position rather than dying on its exit status.
    let dir = repo_with_orphaned_shim("orphan-runtime");

    let o = git(&dir, &["merge", "--no-ff", "side", "-m", "m"]);
    assert!(
        o.ok,
        "an orphaned shim must not break the merge: {}",
        o.stderr
    );
    assert!(
        !o.stderr.contains("migration mode"),
        "the orphan must not have been exec'd: {}",
        o.stderr
    );
    // The framework in the slot still ran — skipping the orphan is not silence.
    assert!(o.stderr.contains("FRAMEWORK_RAN"), "stderr: {}", o.stderr);
    let _ = std::fs::remove_dir_all(&dir);
}

#[cfg(unix)]
#[test]
fn install_clears_an_orphaned_shim() {
    let dir = repo_with_orphaned_shim("orphan-install");
    let hooks = dir.join(".git/hooks");

    let audit = merge_guard::audit(&hooks).unwrap();
    assert_eq!(
        audit.fault(),
        Some(merge_guard::Fault::ShimChained),
        "doctor must see it: {audit:?}"
    );

    let plan = merge_guard::install(&hooks).unwrap();
    assert!(plan.drop_chained, "the orphan must be removed: {plan:?}");
    assert!(!plan.restore_shim, "the slot already has its own shim");
    assert!(
        !hooks.join(merge_guard::CHAINED_NAME).exists(),
        "the orphaned shim must be gone"
    );
    assert_eq!(merge_guard::audit(&hooks).unwrap().fault(), None);

    // The guard survived the cleanup and still bites.
    let o = git_env(
        &dir,
        &[("THEGN_SANDBOX", "1")],
        &["merge", "--no-ff", "side"],
    );
    assert!(!o.ok, "guard must still refuse: {}", o.stderr);
    assert!(
        o.stderr.contains("refusing to merge"),
        "stderr: {}",
        o.stderr
    );
    let _ = std::fs::remove_dir_all(&dir);
}

#[cfg(unix)]
#[test]
fn a_user_hook_still_runs_when_we_own_the_slot() {
    // No framework: we take the slot and chain the user's hook, which must
    // still be able to refuse a merge on its own terms.
    let dir = scratch("userhook");
    must(&dir, &["init", "-q", "-b", "main"]);
    std::fs::write(dir.join("base.txt"), "base\n").unwrap();
    must(&dir, &["add", "-A"]);
    must(&dir, &["commit", "-q", "-m", "base"]);
    must(&dir, &["checkout", "-q", "-b", "side"]);
    std::fs::write(dir.join("side.txt"), "s\n").unwrap();
    must(&dir, &["add", "-A"]);
    must(&dir, &["commit", "-q", "-m", "side"]);
    must(&dir, &["checkout", "-q", "main"]);

    let hooks = dir.join(".git/hooks");
    write_exec(
        &hooks.join(merge_guard::HOOK_NAME),
        "#!/bin/sh\necho USER_HOOK_SAYS_NO >&2\nexit 3\n",
    );
    let plan = merge_guard::install(&hooks).unwrap();
    assert_eq!(plan.placement, Placement::Hook);
    assert_eq!(plan.action, InstallAction::Chained);

    // Not sandboxed → allow path → delegate to the chained user hook, which refuses.
    let o = git(&dir, &["merge", "--no-ff", "side", "-m", "m"]);
    assert!(!o.ok, "the chained user hook must still gate: {}", o.stderr);
    assert!(
        o.stderr.contains("USER_HOOK_SAYS_NO"),
        "stderr: {}",
        o.stderr
    );
    let _ = std::fs::remove_dir_all(&dir);
}
