//! The native-host action registry: [`ActionSpec`] + the `ACTION_SPECS`
//! table that drives palette rows, compact hints, default chords, and the
//! discoverability tests. Extracted from `keymap.rs` (pinned by the file-size
//! ratchet); re-exported there so `crate::keymap::ACTION_SPECS` keeps working.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ActionSpec {
    /// Stable action id; matches [`crate::keymap::Action::key`] and command-palette dispatch.
    pub id: &'static str,
    /// Human label shown in the command palette and help surfaces.
    pub label: &'static str,
    /// Short label for compact bottom-bar hints.
    pub hint: &'static str,
    /// Built-in normal-mode/default chords. Config layers may override these.
    pub default_chords: &'static [&'static str],
    /// Whether this action should be surfaced in the command palette.
    pub palette: bool,
}

/// Native-host action registry: one table drives palette rows, compact hints,
/// and tests that every real host action is discoverable. Keep ids aligned with
/// [`crate::keymap::Action::key`] / [`crate::keymap::Action::from_key`]; legacy aliases stay in `from_key`.
pub const ACTION_SPECS: &[ActionSpec] = &[
    ActionSpec {
        id: "new-worktree",
        label: "New worktree",
        hint: "worktree",
        default_chords: &["Alt w"],
        palette: true,
    },
    ActionSpec {
        id: "new-workspace",
        label: "New workspace",
        hint: "workspace",
        default_chords: &["Alt W"],
        palette: true,
    },
    ActionSpec {
        id: "delete-workspace",
        label: "Delete workspace",
        hint: "remove the active workspace",
        // No default chord — `Alt X` / `Space X` belong to close-worktree, so
        // this action is palette-driven + user-bindable (also reachable from the
        // sidebar row menu's "Remove workspace").
        default_chords: &[],
        palette: true,
    },
    ActionSpec {
        id: "integrate",
        label: "Integrate (fold-actor)",
        hint: "integrate",
        // No default chord — palette-only + user-bindable, gated on
        // [merge_queue].enabled (see palette::build_command_palette_items).
        default_chords: &[],
        palette: true,
    },
    ActionSpec {
        id: "merge-drain",
        label: "Merge queue: drain (agent autopilot)",
        hint: "drain queue",
        // No default chord — palette + the section's `D`; gated on
        // [merge_queue].enabled like the other fold-actor actions.
        default_chords: &[],
        palette: true,
    },
    ActionSpec {
        id: "new-tab",
        label: "New tab — same worktree",
        hint: "tab",
        default_chords: &["Alt t"],
        palette: true,
    },
    ActionSpec {
        id: "new-pane",
        label: "New pane — smart split",
        hint: "smart split",
        default_chords: &["Alt p"],
        palette: true,
    },
    ActionSpec {
        id: "split-down",
        label: "Split pane down",
        hint: "split↓",
        default_chords: &["Alt n"],
        palette: true,
    },
    ActionSpec {
        id: "split-right",
        label: "Split pane right",
        hint: "split→",
        default_chords: &["Alt N"],
        palette: true,
    },
    ActionSpec {
        id: "close-pane",
        label: "Close pane",
        hint: "close pane",
        // No default chord: the smart `close` action (`Alt x`) closes the pane
        // when the tab is split. Kept explicit + rebindable for "always the
        // pane" semantics.
        default_chords: &[],
        palette: true,
    },
    ActionSpec {
        id: "zoom",
        label: "Toggle zoom",
        hint: "zoom",
        default_chords: &["Ctrl Alt z"],
        palette: true,
    },
    ActionSpec {
        id: "sync-panes",
        label: "Toggle sync-panes (broadcast input)",
        hint: "sync",
        default_chords: &["Ctrl Alt y"],
        palette: true,
    },
    ActionSpec {
        id: "save-layout",
        label: "Save layout as…",
        hint: "save layout",
        default_chords: &[],
        palette: true,
    },
    ActionSpec {
        id: "apply-layout",
        label: "Apply saved layout…",
        hint: "apply layout",
        default_chords: &[],
        palette: true,
    },
    ActionSpec {
        id: "export-layout",
        label: "Export layout to file…",
        hint: "export layout",
        default_chords: &[],
        palette: true,
    },
    ActionSpec {
        id: "import-layout",
        label: "Import layout from file…",
        hint: "import layout",
        default_chords: &[],
        palette: true,
    },
    ActionSpec {
        id: "new-worktree-from-template",
        label: "New worktree from template…",
        hint: "template",
        default_chords: &[],
        palette: true,
    },
    ActionSpec {
        id: "cycle-theme",
        label: "Cycle theme",
        hint: "theme",
        default_chords: &["Ctrl Alt t"],
        palette: true,
    },
    ActionSpec {
        id: "switch-font",
        // Single chord `Alt f`; the old redundant `Alt F` alias was dropped so
        // Shift keeps its "up-a-level" meaning everywhere in the Alt layer.
        label: "Switch font",
        hint: "font",
        default_chords: &["Alt f"],
        palette: true,
    },
    ActionSpec {
        id: "close",
        label: "Close (pane or tab)",
        hint: "close",
        default_chords: &["Alt x"],
        palette: true,
    },
    ActionSpec {
        id: "close-tab",
        label: "Close tab",
        hint: "close tab",
        // No default chord: `Alt x` is the smart `close` above. Explicit +
        // rebindable for "close the tab specifically".
        default_chords: &[],
        palette: true,
    },
    ActionSpec {
        id: "close-worktree",
        label: "Remove worktree",
        hint: "remove worktree (from disk)",
        default_chords: &["Alt X"],
        palette: true,
    },
    ActionSpec {
        id: "switch-workspace",
        label: "Switch workspace",
        hint: "switch",
        default_chords: &["Alt o"],
        palette: true,
    },
    ActionSpec {
        id: "switch-account",
        label: "Switch agent account",
        hint: "account",
        default_chords: &["Ctrl Alt a"],
        palette: true,
    },
    ActionSpec {
        id: "switch-bundle",
        label: "Switch env bundle",
        hint: "bundle",
        default_chords: &["Ctrl Alt u"],
        palette: true,
    },
    ActionSpec {
        id: "switch-profile",
        label: "Switch profile",
        hint: "profile",
        default_chords: &["Ctrl Alt g"],
        palette: true,
    },
    ActionSpec {
        id: "prev-tab",
        label: "Previous tab",
        hint: "prev tab",
        default_chords: &["Alt Left"],
        palette: true,
    },
    ActionSpec {
        id: "next-tab",
        label: "Next tab",
        hint: "next tab",
        default_chords: &["Alt Right"],
        palette: true,
    },
    ActionSpec {
        id: "prev-worktree",
        label: "Previous worktree",
        hint: "prev worktree",
        default_chords: &["Alt Up"],
        palette: true,
    },
    ActionSpec {
        id: "next-worktree",
        label: "Next worktree",
        hint: "next worktree",
        default_chords: &["Alt Down"],
        palette: true,
    },
    ActionSpec {
        id: "prev-workspace",
        label: "Previous workspace",
        hint: "prev ws",
        default_chords: &["Shift Alt Up"],
        palette: true,
    },
    ActionSpec {
        id: "next-workspace",
        label: "Next workspace",
        hint: "next ws",
        default_chords: &["Shift Alt Down"],
        palette: true,
    },
    ActionSpec {
        id: "toggle-region",
        label: "Toggle workspaces / terminals",
        hint: "ws↔term",
        default_chords: &["Alt `"],
        palette: true,
    },
    ActionSpec {
        id: "move-item-up",
        label: "Move up (workspace/worktree)",
        hint: "move↑",
        default_chords: &["Ctrl Alt Up"],
        palette: true,
    },
    ActionSpec {
        id: "move-item-down",
        label: "Move down (workspace/worktree)",
        hint: "move↓",
        default_chords: &["Ctrl Alt Down"],
        palette: true,
    },
    ActionSpec {
        id: "move-worktree-to-folder",
        label: "Move worktree to folder…",
        hint: "file worktree",
        default_chords: &[],
        palette: true,
    },
    ActionSpec {
        id: "focus-left",
        label: "Focus left",
        hint: "focus←",
        default_chords: &["Ctrl Left", "Ctrl h"],
        palette: true,
    },
    ActionSpec {
        id: "focus-right",
        label: "Focus right",
        hint: "focus→",
        default_chords: &["Ctrl Right", "Ctrl l"],
        palette: true,
    },
    ActionSpec {
        id: "focus-up",
        label: "Focus up",
        hint: "focus↑",
        default_chords: &["Ctrl Up", "Ctrl k"],
        palette: true,
    },
    ActionSpec {
        id: "focus-down",
        label: "Focus down",
        hint: "focus↓",
        default_chords: &["Ctrl Down", "Ctrl j"],
        palette: true,
    },
    ActionSpec {
        id: "toggle-sidebar",
        label: "Toggle sidebar",
        hint: "sidebar",
        default_chords: &["Ctrl Alt s"],
        palette: true,
    },
    ActionSpec {
        id: "warm-pool-increment",
        label: "Warm pool: add a spare",
        hint: "warm+",
        default_chords: &["Ctrl Alt ="],
        palette: true,
    },
    ActionSpec {
        id: "warm-pool-decrement",
        label: "Warm pool: remove a spare",
        hint: "warm-",
        default_chords: &["Ctrl Alt -"],
        palette: true,
    },
    ActionSpec {
        id: "toggle-panel",
        label: "Toggle diff / PR panel",
        hint: "panel",
        default_chords: &["Ctrl Alt p"],
        palette: true,
    },
    ActionSpec {
        id: "files-drawer",
        label: "Toggle files drawer",
        hint: "drawer",
        default_chords: &["Ctrl Alt f"],
        palette: true,
    },
    ActionSpec {
        id: "toggle-corner",
        label: "Toggle corner overlay (video)",
        hint: "corner",
        default_chords: &["Ctrl Alt o"],
        palette: true,
    },
    ActionSpec {
        id: "focus-sidebar",
        label: "Focus workspace sidebar",
        hint: "sidebar",
        default_chords: &["Alt s"],
        palette: true,
    },
    ActionSpec {
        id: "focus-panel",
        label: "Focus diff / PR panel",
        hint: "panel",
        default_chords: &["Alt ."],
        palette: true,
    },
    ActionSpec {
        id: "toggle-notifications",
        label: "Toggle Notifications panel",
        hint: "notifications",
        default_chords: &["Ctrl Alt i"],
        palette: true,
    },
    ActionSpec {
        id: "open-ci",
        label: "Open CI/CD runs panel",
        hint: "ci",
        default_chords: &[],
        palette: true,
    },
    ActionSpec {
        id: "open-merge-queue",
        label: "Merge queue",
        hint: "merge queue",
        default_chords: &["Ctrl Alt q"],
        palette: true,
    },
    ActionSpec {
        id: "share-worktree-port",
        label: "Share worktree port",
        hint: "share",
        default_chords: &["Alt Shift S"],
        palette: true,
    },
    ActionSpec {
        id: "stop-worktree-share",
        label: "Stop worktree shares",
        hint: "unshare",
        default_chords: &[],
        palette: true,
    },
    ActionSpec {
        id: "open-shares",
        label: "Open shares panel",
        hint: "shares",
        default_chords: &[],
        palette: true,
    },
    ActionSpec {
        id: "palette",
        label: "Command palette",
        hint: "menu",
        default_chords: &["Ctrl Space"],
        palette: true,
    },
    ActionSpec {
        id: "lazygit",
        label: "Open lazygit",
        hint: "lazygit",
        default_chords: &["Alt g"],
        palette: true,
    },
    ActionSpec {
        id: "yazi",
        label: "Open yazi drawer",
        hint: "yazi",
        default_chords: &["Alt y"],
        palette: true,
    },
    ActionSpec {
        id: "editor",
        label: "Open editor",
        hint: "editor",
        default_chords: &["Alt e"],
        palette: true,
    },
    ActionSpec {
        id: "show-diff",
        label: "Open git diff",
        hint: "diff",
        default_chords: &["Alt /"],
        palette: true,
    },
    ActionSpec {
        id: "git-push",
        label: "Git push (current branch)",
        hint: "push",
        default_chords: &[],
        palette: true,
    },
    ActionSpec {
        id: "git-pull",
        label: "Git pull (current branch)",
        hint: "pull",
        default_chords: &[],
        palette: true,
    },
    ActionSpec {
        id: "git-fetch",
        label: "Git fetch (all remotes, prune)",
        hint: "fetch",
        default_chords: &[],
        palette: true,
    },
    ActionSpec {
        id: "rollback",
        label: "Rollback / discard changes…",
        hint: "rollback",
        default_chords: &[],
        palette: true,
    },
    ActionSpec {
        id: "scroll-up",
        label: "Scroll pane up",
        hint: "scroll↑",
        default_chords: &["Shift PageUp", "PageUp"],
        palette: true,
    },
    ActionSpec {
        id: "scroll-down",
        label: "Scroll pane down",
        hint: "scroll↓",
        default_chords: &["Shift PageDown", "PageDown"],
        palette: true,
    },
    ActionSpec {
        id: "copy-pane",
        label: "Copy pane contents",
        hint: "copy",
        default_chords: &["Ctrl Alt c"],
        palette: true,
    },
    ActionSpec {
        id: "search-pane",
        label: "Search pane history",
        hint: "search",
        default_chords: &["/"],
        palette: true,
    },
    ActionSpec {
        id: "search-global",
        label: "Search across all panes (worktree scope)",
        hint: "search all",
        default_chords: &["Ctrl /"],
        palette: true,
    },
    ActionSpec {
        id: "toggle-key-lock",
        label: "Lock/unlock keybinds (pass through)",
        hint: "lock",
        default_chords: &["Ctrl g"],
        palette: true,
    },
    ActionSpec {
        id: "mode-normal",
        label: "Switch to Normal mode",
        hint: "normal",
        default_chords: &["Ctrl Alt n"],
        palette: true,
    },
    ActionSpec {
        id: "mode-vim-normal",
        label: "Switch to Vim-normal mode",
        hint: "vim",
        default_chords: &["Ctrl Alt v"],
        palette: true,
    },
    ActionSpec {
        id: "mode-vim-insert",
        label: "Switch to Vim-insert mode",
        hint: "insert",
        default_chords: &[],
        palette: true,
    },
    ActionSpec {
        id: "mode-emacs",
        label: "Switch to Emacs mode",
        hint: "emacs",
        default_chords: &["Ctrl Alt e"],
        palette: true,
    },
    ActionSpec {
        id: "toggle-strip",
        label: "Toggle pin strip",
        hint: "pins",
        default_chords: &["Ctrl Alt b"],
        palette: true,
    },
    ActionSpec {
        id: "grow-strip",
        label: "Grow pin strip",
        hint: "pins+",
        default_chords: &["Ctrl Alt ]"],
        palette: true,
    },
    ActionSpec {
        id: "shrink-strip",
        label: "Shrink pin strip",
        hint: "pins-",
        default_chords: &["Ctrl Alt ["],
        palette: true,
    },
    ActionSpec {
        id: "promote-pin",
        label: "Promote pane to pin strip",
        hint: "pin pane",
        default_chords: &["Ctrl Alt P"],
        palette: true,
    },
    ActionSpec {
        id: "unpin",
        label: "Unpin focused/first pin",
        hint: "unpin",
        default_chords: &["Ctrl Alt U"],
        palette: true,
    },
    ActionSpec {
        id: "quit",
        label: "Quit superzej",
        hint: "quit",
        default_chords: &["Ctrl q"],
        palette: true,
    },
    // Media transport (optional [media] feature). Leader: `Alt m`. All inert when
    // media is disabled; surfaced in the palette so they're discoverable.
    ActionSpec {
        id: "media-play-pause",
        label: "Media: Play/Pause",
        hint: "play/pause",
        default_chords: &["Alt m m"],
        palette: true,
    },
    ActionSpec {
        id: "media-next",
        label: "Media: Next track",
        hint: "next",
        default_chords: &["Alt m n"],
        palette: true,
    },
    ActionSpec {
        id: "media-previous",
        label: "Media: Previous track",
        hint: "prev",
        default_chords: &["Alt m p"],
        palette: true,
    },
    ActionSpec {
        id: "media-shuffle-toggle",
        label: "Media: Toggle shuffle",
        hint: "shuffle",
        default_chords: &["Alt m s"],
        palette: true,
    },
    ActionSpec {
        id: "media-loop-cycle",
        label: "Media: Cycle repeat",
        hint: "loop",
        default_chords: &["Alt m r"],
        palette: true,
    },
    ActionSpec {
        id: "media-volume-up",
        label: "Media: Volume up",
        hint: "vol+",
        default_chords: &["Alt m k"],
        palette: true,
    },
    ActionSpec {
        id: "media-volume-down",
        label: "Media: Volume down",
        hint: "vol−",
        default_chords: &["Alt m j"],
        palette: true,
    },
    ActionSpec {
        id: "media-select-playlist",
        label: "Media: Select playlist…",
        hint: "playlist",
        default_chords: &["Alt m l"],
        palette: true,
    },
    ActionSpec {
        id: "media-select-player",
        label: "Media: Select player…",
        hint: "player",
        default_chords: &["Alt m o"],
        palette: true,
    },
    // Notification routing (items 426/427).
    ActionSpec {
        id: "notify-dnd-toggle",
        label: "Notifications: Toggle do-not-disturb",
        hint: "dnd",
        default_chords: &["Ctrl Alt d"],
        palette: true,
    },
    ActionSpec {
        id: "notify-mode-cycle",
        label: "Notifications: Cycle routing mode",
        hint: "notif mode",
        default_chords: &["Ctrl Alt m"],
        palette: true,
    },
    ActionSpec {
        id: "attention-next",
        label: "Jump to next attention",
        hint: "needs you",
        default_chords: &["Alt a"],
        palette: true,
    },
    ActionSpec {
        id: "mark-all-read",
        label: "Notifications: Mark all as read",
        hint: "mark all read",
        default_chords: &["Alt Shift R"],
        palette: true,
    },
];

pub fn action_specs() -> &'static [ActionSpec] {
    ACTION_SPECS
}
