//! v38: per-sandbox iroh auth tokens — the store behind the call-home reach's
//! security gate.
//!
//! When the compositor provisions a sandbox it mints a random token, persists it
//! here keyed to the sandbox id, and injects it as `THEGN_SANDBOX_AUTH`. When
//! the sandbox's agent dials home it presents the token; the home endpoint's
//! verifier calls [`Db::verify_iroh_token`] to resolve it back to the authorized
//! sandbox id (or reject). Tokens are revoked on teardown.
//!
//! The token itself is generated by the caller (the host, which has a CSPRNG);
//! this layer hashes it and only ever stores + matches the **sha-256 hex** of
//! the secret — never the plaintext bearer token. This upholds the same
//! hashed-secret invariant as `pairings.token_hash` and `proxy_virtual_keys`
//! (`db_control`): a leak of `thegn.db` (world-readable under a permissive
//! umask, or any backup of the state dir) yields only hashes, not live
//! `THEGN_SANDBOX_AUTH` tokens. The caller keeps passing the raw token; hashing
//! at the store boundary makes it impossible for a caller to persist plaintext.
//!
//! `sha256` here is a small self-contained implementation (core has no crypto
//! dependency); the svc/host crates that mint control-plane tokens use the `sha2`
//! crate, but this store must stay in `thegn-core` (behind the `Db` seam) so the
//! home-endpoint verifier can resolve tokens without a service round-trip.

use anyhow::Result;
use rusqlite::{Connection, params};

use crate::db::Db;

/// sha-256 → 64-char lowercase hex. Self-contained (FIPS 180-4) so the token
/// store keeps the codebase's "secrets never land in the DB in plaintext"
/// invariant without pulling a crypto crate into substrate-`core`.
pub(crate) fn sha256_hex(input: &str) -> String {
    #[rustfmt::skip]
    const K: [u32; 64] = [
        0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
        0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
        0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
        0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
        0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
        0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
        0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
        0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
    ];
    let mut h: [u32; 8] = [
        0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19,
    ];
    // Pre-processing: append 0x80, pad with zeros to 56 mod 64, then the 64-bit
    // big-endian bit length.
    let mut msg = input.as_bytes().to_vec();
    let bit_len = (msg.len() as u64) * 8;
    msg.push(0x80);
    while msg.len() % 64 != 56 {
        msg.push(0);
    }
    msg.extend_from_slice(&bit_len.to_be_bytes());

    for chunk in msg.chunks_exact(64) {
        let mut w = [0u32; 64];
        for (i, word) in w.iter_mut().take(16).enumerate() {
            *word = u32::from_be_bytes([
                chunk[i * 4],
                chunk[i * 4 + 1],
                chunk[i * 4 + 2],
                chunk[i * 4 + 3],
            ]);
        }
        for i in 16..64 {
            let s0 = w[i - 15].rotate_right(7) ^ w[i - 15].rotate_right(18) ^ (w[i - 15] >> 3);
            let s1 = w[i - 2].rotate_right(17) ^ w[i - 2].rotate_right(19) ^ (w[i - 2] >> 10);
            w[i] = w[i - 16]
                .wrapping_add(s0)
                .wrapping_add(w[i - 7])
                .wrapping_add(s1);
        }
        let [mut a, mut b, mut c, mut d, mut e, mut f, mut g, mut hh] = h;
        for i in 0..64 {
            let s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
            let ch = (e & f) ^ ((!e) & g);
            let t1 = hh
                .wrapping_add(s1)
                .wrapping_add(ch)
                .wrapping_add(K[i])
                .wrapping_add(w[i]);
            let s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
            let maj = (a & b) ^ (a & c) ^ (b & c);
            let t2 = s0.wrapping_add(maj);
            hh = g;
            g = f;
            f = e;
            e = d.wrapping_add(t1);
            d = c;
            c = b;
            b = a;
            a = t1.wrapping_add(t2);
        }
        for (dst, v) in h.iter_mut().zip([a, b, c, d, e, f, g, hh]) {
            *dst = dst.wrapping_add(v);
        }
    }
    let mut out = String::with_capacity(64);
    for word in h {
        out.push_str(&format!("{word:08x}"));
    }
    out
}

/// Create the `iroh_tokens` table. Idempotent (`IF NOT EXISTS`), so re-running an
/// already-migrated DB is a no-op.
pub(crate) fn migrate_v38(conn: &Connection) -> Result<()> {
    conn.execute_batch(
        r#"
        CREATE TABLE IF NOT EXISTS iroh_tokens (
            sandbox    TEXT PRIMARY KEY,
            -- The sha-256 hex of the bearer token, NOT the plaintext token.
            -- Column name kept for schema stability; `mint_iroh_token` /
            -- `verify_iroh_token` hash at the boundary.
            token      TEXT NOT NULL,
            created_ms INTEGER NOT NULL
        );
        CREATE INDEX IF NOT EXISTS idx_iroh_tokens_token ON iroh_tokens(token);
        "#,
    )?;
    Ok(())
}

impl Db {
    /// Record (or replace) the auth token for a sandbox. The caller supplies a
    /// freshly-generated random `token`; only its sha-256 hash is persisted, so
    /// the plaintext bearer token never lands in the DB.
    pub fn mint_iroh_token(&self, sandbox: &str, token: &str, created_ms: i64) -> Result<()> {
        let hash = sha256_hex(token);
        self.conn().execute(
            "INSERT INTO iroh_tokens (sandbox, token, created_ms) VALUES (?1, ?2, ?3)
             ON CONFLICT(sandbox) DO UPDATE SET token = excluded.token, created_ms = excluded.created_ms",
            params![sandbox, hash, created_ms],
        )?;
        Ok(())
    }

    /// Resolve a presented token to the sandbox id it authorizes, or `None` if no
    /// live token matches (unminted / revoked / forged). The presented plaintext
    /// is hashed and matched against the stored sha-256 hex.
    pub fn verify_iroh_token(&self, token: &str) -> Result<Option<String>> {
        let hash = sha256_hex(token);
        let sandbox = self
            .conn()
            .query_row(
                "SELECT sandbox FROM iroh_tokens WHERE token = ?1",
                params![hash],
                |r| r.get::<_, String>(0),
            )
            .ok();
        Ok(sandbox)
    }

    /// Revoke a sandbox's token (on teardown). Best-effort; a missing row is fine.
    pub fn revoke_iroh_token(&self, sandbox: &str) -> Result<()> {
        self.conn().execute(
            "DELETE FROM iroh_tokens WHERE sandbox = ?1",
            params![sandbox],
        )?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use crate::db::Db;
    use rusqlite::params;

    #[test]
    fn mint_verify_revoke_round_trip() {
        let db = Db::open_memory().unwrap();
        db.mint_iroh_token("wt-a", "tok-secret-a", 1_000).unwrap();
        db.mint_iroh_token("wt-b", "tok-secret-b", 2_000).unwrap();

        // Presenting a token resolves to its sandbox.
        assert_eq!(
            db.verify_iroh_token("tok-secret-a").unwrap().as_deref(),
            Some("wt-a")
        );
        assert_eq!(
            db.verify_iroh_token("tok-secret-b").unwrap().as_deref(),
            Some("wt-b")
        );
        // A forged / unknown token resolves to nothing.
        assert_eq!(db.verify_iroh_token("nope").unwrap(), None);

        // Revoked tokens no longer verify.
        db.revoke_iroh_token("wt-a").unwrap();
        assert_eq!(db.verify_iroh_token("tok-secret-a").unwrap(), None);
        assert_eq!(
            db.verify_iroh_token("tok-secret-b").unwrap().as_deref(),
            Some("wt-b")
        );
    }

    #[test]
    fn re_minting_replaces_the_token() {
        let db = Db::open_memory().unwrap();
        db.mint_iroh_token("wt", "old", 1).unwrap();
        db.mint_iroh_token("wt", "new", 2).unwrap();
        // The old token is gone; only the newest is valid.
        assert_eq!(db.verify_iroh_token("old").unwrap(), None);
        assert_eq!(db.verify_iroh_token("new").unwrap().as_deref(), Some("wt"));
    }

    #[test]
    fn migration_is_idempotent() {
        // Opening twice (re-running migrations) must not error.
        let db = Db::open_memory().unwrap();
        crate::db_iroh::migrate_v38(db.conn()).expect("re-migrate");
        db.mint_iroh_token("wt", "t", 1).unwrap();
        assert_eq!(db.verify_iroh_token("t").unwrap().as_deref(), Some("wt"));
    }

    #[test]
    fn sha256_matches_known_vectors() {
        use crate::db_iroh::sha256_hex;
        // FIPS 180-4 / RFC test vectors.
        assert_eq!(
            sha256_hex(""),
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        );
        assert_eq!(
            sha256_hex("abc"),
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
        );
        // A message spanning two 64-byte blocks exercises the multi-chunk path.
        assert_eq!(
            sha256_hex("abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq"),
            "248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1"
        );
    }

    #[test]
    fn plaintext_token_is_never_stored() {
        let db = Db::open_memory().unwrap();
        let secret = "szi_deadbeefcafef00d";
        db.mint_iroh_token("wt-a", secret, 1_000).unwrap();
        // The raw token must NOT appear in the DB — only its sha-256 hash.
        let stored: String = db
            .conn()
            .query_row(
                "SELECT token FROM iroh_tokens WHERE sandbox='wt-a'",
                [],
                |r| r.get(0),
            )
            .unwrap();
        assert_ne!(stored, secret, "plaintext token leaked into the DB");
        assert_eq!(stored, crate::db_iroh::sha256_hex(secret));
        assert_eq!(stored.len(), 64, "sha-256 hex is 64 chars");
        // A row lookup by the raw plaintext finds nothing (only the hash is keyed).
        let by_plain: Option<String> = db
            .conn()
            .query_row(
                "SELECT sandbox FROM iroh_tokens WHERE token=?1",
                params![secret],
                |r| r.get(0),
            )
            .ok();
        assert_eq!(by_plain, None);
        // But verify() (which hashes) still resolves it.
        assert_eq!(db.verify_iroh_token(secret).unwrap().as_deref(), Some("wt-a"));
    }
}
