//! thegn-core — the substrate-agnostic heart of thegn.
//!
//! Everything here is independent of the UI substrate (the native host): SQLite
//! state, git/worktree/repo logic, the sandbox + remote transport seams, config
//! layering, the theme palette, and structured logging. No module here references
//! a multiplexer, a terminal emulator, or a renderer — that is enforced by keeping
//! `tokio`, `termwiz`, and the native service crates out of this crate's
//! dependency set. The `keymap` module is the keybinding *registry* (effective
//! bindings + collision detection for the cheatsheet/`keys validate`); the host
//! owns terminal chord→Action routing.

pub mod account;
pub mod acp;
pub mod activity;
pub mod aggregate;
pub mod attention;
pub mod blame;
pub mod bundle;
pub mod capabilities;
pub mod capacity;
pub mod ci;
pub mod config;
pub mod config_daemon;
pub mod config_defaults;
pub mod config_env_tables;
pub mod config_issues;
pub mod config_media;
pub mod config_observe;
pub mod config_placement;
pub mod config_resolve;
pub mod config_theme;
pub mod config_ui;
pub mod config_write;
pub mod control;
pub mod control_wire;
pub mod custom_cmd;
pub mod db;
mod db_account;
mod db_aux;
mod db_cache;
pub mod db_compute;
mod db_control;
mod db_glyph;
mod db_hibernate;
mod db_intent;
mod db_iroh;
pub mod db_migrate;
mod db_notification;
pub mod db_placement;
mod db_pool;
mod db_proxy;
mod db_semantic;
mod db_trust;
mod db_workspace;
mod db_zones;
pub mod debug;
pub mod devenv;
pub mod diff_highlight;
pub mod diff_sbs;
pub mod direnv;
pub mod disk;
pub mod dns_filter;
pub mod env;
pub mod envbuild;
pub mod envplan;
pub mod event_bus;
pub mod fold;
pub mod forge;
pub mod forward;
pub mod frecency;
pub mod github;
pub mod gitrefs;
pub mod gitviz;
pub mod grants;
pub mod history;
pub mod host;
pub mod host_config;
pub mod host_db;
pub mod host_machine;
pub mod host_probe;
pub mod i18n;
pub mod image;
pub mod inventory;
pub mod iroh_wire;
pub mod issue;
pub mod keymap;
pub mod layout_import;
pub mod lifecycle;
pub mod loc;
pub mod log;
pub mod log_trace;
pub mod log_view;
pub mod managed_tool;
pub mod mcp;
pub mod media;
pub mod merge_guard;
pub mod merge_lifecycle;
pub mod metrics;
pub mod models;
pub mod msg;
pub mod notification;
pub mod notification_route;
pub mod out;
pub mod patch;
pub mod picker;
pub mod placement;
pub mod plugin_api;
pub mod preview;
pub mod profile;
pub mod projection;
pub mod proxy;
pub mod rebase_todo;
pub mod reflog;
pub mod registers;
pub mod remote;
pub mod repo;
pub mod repo_trust;
pub mod revtunnel;
pub mod sandbox;
pub mod sandbox_backend;
pub mod sandbox_mounts;
pub mod sandbox_prefetch;
pub mod sandbox_preflight;
pub mod scheduler;
pub mod search;
pub mod semantic;
pub mod semantic_graph;
pub mod share;
pub mod snapshot_meta;
pub mod spillover;
pub mod ssh_creds;
pub mod startup;
pub mod store;
pub mod syncstate;
pub mod term_snapshot;
pub mod termcaps;
#[cfg(test)]
mod testenv;
pub mod theme;
pub mod toolchain;
pub mod trust_class;
pub mod util;
pub mod viz;
pub mod work;
pub mod worktree;
pub mod yazi;
pub mod zone;
