#!/usr/bin/env bash
# make-app.sh — generate a macOS `thegn.app` launcher bundle.
#
# thegn is a TUI, so the bundle is a launcher: double-clicking it (Spotlight,
# Raycast, Alfred, the Dock, /Applications) opens a terminal emulator running
# `thegn`. It is the Darwin counterpart to the `.desktop` entry `install.sh`
# writes on Linux/BSD — same job, different registry.
#
# The bundle is generated LOCALLY (by install.sh, `just macos-app`, or by hand),
# never downloaded. That matters: a locally created bundle carries no
# `com.apple.quarantine` xattr, so Gatekeeper does not block it and no code
# signing / notarization is involved. Shipping a prebuilt .app would need both.
#
#   ./packaging/macos/make-app.sh --bin ~/.local/bin/thegn
#   ./packaging/macos/make-app.sh --bin "$(command -v thegn)" --dest /Applications
#
# Re-running overwrites an existing bundle of the same name in place.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

usage() {
  cat >&2 <<'EOF'
usage: make-app.sh [options]

  --bin PATH                thegn binary to launch (default: `thegn` on PATH)
  --dest DIR                where to write the bundle (default: ~/Applications)
  --name NAME               bundle/app name (default: thegn)
  --icon PATH               .icns icon (default: packaging/macos/thegn.icns)
  --terminal PATH           preferred terminal binary; the launcher probes for
                            one at runtime if unset or missing
  --alacritty-config PATH   bundled alacritty profile to use when the chosen
                            terminal is alacritty
  --env KEY=VALUE           export KEY in the launched session (repeatable).
                            e.g. --env THEGN_LOG=info --env THEGN_PERF=1 for a
                            watchable build, or --env THEGN_CHANNEL=dev
  --dry-run                 print the plan without writing anything
EOF
}

bin=""
dest="$HOME/Applications"
name="thegn"
icon="$here/thegn.icns"
terminal=""
alacritty_config=""
envs=()
dry_run=0

while (($#)); do
  case "$1" in
  --bin)
    bin="${2-}"
    shift
    ;;
  --dest)
    dest="${2-}"
    shift
    ;;
  --name)
    name="${2-}"
    shift
    ;;
  --icon)
    icon="${2-}"
    shift
    ;;
  --terminal)
    terminal="${2-}"
    shift
    ;;
  --alacritty-config)
    alacritty_config="${2-}"
    shift
    ;;
  --env)
    if [[ ${2-} != *=* ]]; then
      echo "make-app.sh: --env wants KEY=VALUE, got: ${2-}" >&2
      exit 2
    fi
    envs+=("$2")
    shift
    ;;
  --dry-run) dry_run=1 ;;
  -h | --help)
    usage
    exit 0
    ;;
  *)
    echo "make-app.sh: unknown argument: $1" >&2
    usage
    exit 2
    ;;
  esac
  shift
done

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "make-app.sh: macOS only (on Linux/BSD install.sh writes a .desktop entry)" >&2
  exit 1
fi

if [[ -z $bin ]]; then
  bin="$(command -v thegn || true)"
fi
if [[ -z $bin ]]; then
  echo "make-app.sh: no thegn binary given and none on PATH — pass --bin PATH" >&2
  exit 1
fi
# Absolute + resolved: the launcher runs with launchd's PATH and no cwd of ours.
# A `~/.nix-profile` or `~/.local/bin` path is kept as-is (it survives upgrades);
# only a relative path is made absolute.
[[ $bin == /* ]] || bin="$(cd "$(dirname "$bin")" && pwd)/$(basename "$bin")"
if [[ ! -x $bin ]]; then
  echo "make-app.sh: not executable: $bin" >&2
  exit 1
fi

app="$dest/$name.app"
version="$("$bin" --version 2>/dev/null | awk '{print $2}')"
version="${version:-0.0.0}"
# CFBundleVersion must be numeric-dotted; a pre-release suffix (0.1.0-alpha.2)
# is only legal in CFBundleShortVersionString.
short_version="$version"
build_version="${version%%-*}"

if ((dry_run)); then
  echo "dry-run: no files will be changed"
  echo "$app"
  echo "  Contents/MacOS/$name        -> launcher (opens a terminal running $bin)"
  echo "  Contents/Resources/$name.icns <- $icon"
  echo "  Contents/Resources/$name.command -> Terminal.app fallback runner"
  echo "  Contents/Info.plist         -> CFBundleShortVersionString $short_version"
  exit 0
fi

mkdir -p "$app/Contents/MacOS" "$app/Contents/Resources"

login_shell="${SHELL:-/bin/zsh}"

q() { printf '%q' "$1"; }
bin_q="$(q "$bin")"
alacritty_config_q=""
[[ -n $alacritty_config ]] && alacritty_config_q="$(q "$alacritty_config")"

# ── Contents/Resources/common.sh — shared by both entry points ────────────────
# Baked values first (unquoted heredoc), then the static body (quoted), so the
# generated script contains literal paths and no expansion surprises.
{
  env_q=""
  for kv in ${envs+"${envs[@]}"}; do env_q+=" $(q "$kv")"; done
  cat <<EOF
#!/bin/bash
# Generated by packaging/macos/make-app.sh — do not edit; re-run the generator.
THEGN_BIN=$bin_q
THEGN_LOGIN_SHELL=$(q "$login_shell")
THEGN_ALACRITTY_CFG=${alacritty_config_q:-""}
THEGN_ENV=($env_q)
APP_NAME=$(q "$name")
EOF
  cat <<'EOF'

# A GUI launch inherits launchd's PATH, which contains none of the usual install
# prefixes (nix profiles, ~/.local/bin, Homebrew). Everything here is resolved by
# absolute path instead.
THEGN_DIRS=(
  "$(dirname "$THEGN_BIN")"
  "$HOME/.nix-profile/bin"
  "/etc/profiles/per-user/$USER/bin"
  "/run/current-system/sw/bin"
  "$HOME/.local/bin"
  "/opt/homebrew/bin"
  "/usr/local/bin"
  "$HOME/.cargo/bin"
)

# GUI launches have nowhere to print to, so a failure has to be shown, not
# logged — otherwise the icon bounces once and nothing happens.
alert() {
  /usr/bin/osascript -e "display alert \"$APP_NAME\" message \"$1\" as critical" >/dev/null 2>&1 || true
  echo "$APP_NAME: $1" >&2
}

# Echo a usable thegn binary. The baked path wins; the search covers the case
# where the install moved (a re-installed nix profile, a rebuilt ~/.local/bin).
resolve_bin() {
  if [ -x "$THEGN_BIN" ]; then
    echo "$THEGN_BIN"
    return 0
  fi
  for d in "${THEGN_DIRS[@]}"; do
    if [ -x "$d/thegn" ]; then
      echo "$d/thegn"
      return 0
    fi
  done
  return 1
}

# The command line a terminal is asked to run: a LOGIN shell, so thegn sees the
# same PATH/env an interactive terminal would (it shells out to git, gh, fzf,
# lazygit, delta) instead of launchd's bare environment.
#
# $2 is the resolved terminal (a path, or empty for the Terminal.app fallback).
# THEGN_ALACRITTY_CONFIG is exported ONLY when Alacritty is the terminal that
# will actually run: it tells thegn's font picker which file to patch, and
# Alacritty is 4th of 5 candidates here. Exported unconditionally, a bundle that
# resolved to Ghostty still pointed the picker at the Alacritty profile — so
# "Switch font" edited a file nothing was reading and reported success.
thegn_command() {
  local bin="$1" term="${2:-}" pre="" kv
  if [ -n "$THEGN_ALACRITTY_CFG" ] && [ "$(basename "$term")" = alacritty ]; then
    pre="export THEGN_ALACRITTY_CONFIG=$(printf '%q' "$THEGN_ALACRITTY_CFG"); "
  fi
  # `${arr+"${arr[@]}"}` — an empty array under `set -u` is an error in the
  # bash 3.2 that ships with macOS.
  for kv in ${THEGN_ENV+"${THEGN_ENV[@]}"}; do
    pre="${pre}export ${kv%%=*}=$(printf '%q' "${kv#*=}"); "
  done
  printf '%sexec %s' "$pre" "$(printf '%q' "$bin")"
}
EOF
} >"$app/Contents/Resources/common.sh"
chmod 0644 "$app/Contents/Resources/common.sh"

# ── Contents/MacOS/<name> — the bundle executable ────────────────────────────
cat >"$app/Contents/MacOS/$name" <<EOF
#!/bin/bash
# Generated by packaging/macos/make-app.sh — do not edit; re-run the generator.
set -uo pipefail
RES="\$(cd -- "\$(dirname -- "\$0")/../Resources" && pwd)"
# shellcheck source=/dev/null
. "\$RES/common.sh"
TERM_PREF=$(q "$terminal")
EOF
cat >>"$app/Contents/MacOS/$name" <<'EOF'

bin="$(resolve_bin)" || {
  alert "thegn binary not found. Re-run ./install.sh (or 'just macos-app') to point this app at it."
  exit 1
}
# Terminal emulators, most-preferred first. Bundle paths are checked directly
# because a Mac terminal's CLI is usually NOT on PATH — Ghostty, kitty, WezTerm
# and Alacritty all ship as .app bundles whose binary lives inside.
candidates=(
  "$TERM_PREF"
  "$HOME/Applications/Ghostty.app/Contents/MacOS/ghostty"
  "/Applications/Ghostty.app/Contents/MacOS/ghostty"
  "$HOME/Applications/WezTerm.app/Contents/MacOS/wezterm"
  "/Applications/WezTerm.app/Contents/MacOS/wezterm"
  "$HOME/Applications/kitty.app/Contents/MacOS/kitty"
  "/Applications/kitty.app/Contents/MacOS/kitty"
  "$HOME/Applications/Alacritty.app/Contents/MacOS/alacritty"
  "/Applications/Alacritty.app/Contents/MacOS/alacritty"
)
# Nix/Homebrew installs put real CLI binaries in the same prefixes thegn lives in.
for d in "${THEGN_DIRS[@]}"; do
  for t in ghostty wezterm kitty alacritty; do
    candidates+=("$d/$t")
  done
done

term=""
for c in "${candidates[@]}"; do
  if [ -n "$c" ] && [ -x "$c" ]; then
    term="$c"
    break
  fi
done

# Built AFTER the terminal is resolved — the env it bakes in depends on which
# terminal will run it (see `thegn_command`).
cmd="$(thegn_command "$bin" "$term")"

if [ -n "$term" ]; then
  case "$(basename "$term")" in
  ghostty) exec "$term" -e "$THEGN_LOGIN_SHELL" -l -c "$cmd" ;;
  wezterm) exec "$term" start -- "$THEGN_LOGIN_SHELL" -l -c "$cmd" ;;
  kitty) exec "$term" "$THEGN_LOGIN_SHELL" -l -c "$cmd" ;;
  alacritty)
    if [ -n "$THEGN_ALACRITTY_CFG" ] && [ -f "$THEGN_ALACRITTY_CFG" ]; then
      exec "$term" --config-file "$THEGN_ALACRITTY_CFG" -e "$THEGN_LOGIN_SHELL" -l -c "$cmd"
    fi
    exec "$term" -e "$THEGN_LOGIN_SHELL" -l -c "$cmd"
    ;;
  esac
fi

# Last resort: Terminal.app, which is on every Mac. It runs a `.command` file in
# a login shell of its own, so the runner just execs the binary.
exec /usr/bin/open -a Terminal "$RES/$APP_NAME.command"
EOF
chmod 0755 "$app/Contents/MacOS/$name"

# ── Contents/Resources/<name>.command — the Terminal.app runner ──────────────
cat >"$app/Contents/Resources/$name.command" <<'EOF'
#!/bin/bash
# Generated by packaging/macos/make-app.sh — do not edit; re-run the generator.
# Terminal.app opens .command files in a login shell, so no re-exec is needed.
set -uo pipefail
RES="$(cd -- "$(dirname -- "$0")" && pwd)"
# shellcheck source=/dev/null
. "$RES/common.sh"
bin="$(resolve_bin)" || {
  alert "thegn binary not found. Re-run ./install.sh (or 'just macos-app')."
  exit 1
}
# Same `export …; exec …` line the bundle executable hands its terminal, so the
# baked environment applies on this path too. No terminal argument: this runner
# IS the Terminal.app fallback, which is never Alacritty.
eval "$(thegn_command "$bin" "")"
EOF
chmod 0755 "$app/Contents/Resources/$name.command"

# ── Icon ─────────────────────────────────────────────────────────────────────
if [[ -f $icon ]]; then
  cp "$icon" "$app/Contents/Resources/$name.icns"
else
  echo "make-app.sh: warning: $icon missing — the app will use a generic icon" \
    "(regenerate with 'python3 scripts/gen-owl-icns.py')" >&2
fi

# ── Info.plist ───────────────────────────────────────────────────────────────
cat >"$app/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>$name</string>
  <key>CFBundleDisplayName</key><string>$name</string>
  <key>CFBundleExecutable</key><string>$name</string>
  <key>CFBundleIdentifier</key><string>com.github.blakeashleyjr.$name</string>
  <key>CFBundleIconFile</key><string>$name</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>$short_version</string>
  <key>CFBundleVersion</key><string>$build_version</string>
  <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
  <key>LSMinimumSystemVersion</key><string>11.0</string>
  <key>NSHighResolutionCapable</key><true/>
  <!-- Deliberately NOT LSUIElement: the launcher execs into the terminal
       emulator, so LaunchServices ends up tracking the terminal and no
       windowless thegn process lingers in the Dock. Marking it an agent would
       buy nothing, and some launchers (Raycast, the app switcher) hide them. -->
</dict>
</plist>
EOF
printf 'APPL????' >"$app/Contents/PkgInfo"

# Bump the bundle mtime and re-register so Spotlight/Raycast/the Dock pick up a
# re-generated bundle immediately instead of serving a stale cached copy.
touch "$app"
lsregister=/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister
[[ -x $lsregister ]] && "$lsregister" -f "$app" >/dev/null 2>&1 || true

echo "wrote app bundle: $app"
echo "  launches: $bin (in a terminal window; Spotlight/Raycast/Dock searchable as '$name')"
