//! v38: per-sandbox iroh auth tokens — the store behind the call-home reach's
//! security gate.
//!
//! When the compositor provisions a sandbox it mints a random token, persists it
//! here keyed to the sandbox id, and injects it as `SUPERZEJ_SANDBOX_AUTH`. When
//! the sandbox's agent dials home it presents the token; the home endpoint's
//! verifier calls [`Db::verify_iroh_token`] to resolve it back to the authorized
//! sandbox id (or reject). Tokens are revoked on teardown.
//!
//! The token itself is generated by the caller (the host, which has a CSPRNG);
//! this layer only stores + matches opaque strings, so it stays pure and testable.

use anyhow::Result;
use rusqlite::{Connection, params};

use crate::db::Db;

/// Create the `iroh_tokens` table. Idempotent (`IF NOT EXISTS`), so re-running an
/// already-migrated DB is a no-op.
pub(crate) fn migrate_v38(conn: &Connection) -> Result<()> {
    conn.execute_batch(
        r#"
        CREATE TABLE IF NOT EXISTS iroh_tokens (
            sandbox    TEXT PRIMARY KEY,
            token      TEXT NOT NULL,
            created_ms INTEGER NOT NULL
        );
        CREATE INDEX IF NOT EXISTS idx_iroh_tokens_token ON iroh_tokens(token);
        "#,
    )?;
    Ok(())
}

impl Db {
    /// Record (or replace) the auth token for a sandbox. The caller supplies a
    /// freshly-generated random `token`.
    pub fn mint_iroh_token(&self, sandbox: &str, token: &str, created_ms: i64) -> Result<()> {
        self.conn().execute(
            "INSERT INTO iroh_tokens (sandbox, token, created_ms) VALUES (?1, ?2, ?3)
             ON CONFLICT(sandbox) DO UPDATE SET token = excluded.token, created_ms = excluded.created_ms",
            params![sandbox, token, created_ms],
        )?;
        Ok(())
    }

    /// Resolve a presented token to the sandbox id it authorizes, or `None` if no
    /// live token matches (unminted / revoked / forged).
    pub fn verify_iroh_token(&self, token: &str) -> Result<Option<String>> {
        let sandbox = self
            .conn()
            .query_row(
                "SELECT sandbox FROM iroh_tokens WHERE token = ?1",
                params![token],
                |r| r.get::<_, String>(0),
            )
            .ok();
        Ok(sandbox)
    }

    /// Revoke a sandbox's token (on teardown). Best-effort; a missing row is fine.
    pub fn revoke_iroh_token(&self, sandbox: &str) -> Result<()> {
        self.conn().execute(
            "DELETE FROM iroh_tokens WHERE sandbox = ?1",
            params![sandbox],
        )?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use crate::db::Db;

    #[test]
    fn mint_verify_revoke_round_trip() {
        let db = Db::open_memory().unwrap();
        db.mint_iroh_token("wt-a", "tok-secret-a", 1_000).unwrap();
        db.mint_iroh_token("wt-b", "tok-secret-b", 2_000).unwrap();

        // Presenting a token resolves to its sandbox.
        assert_eq!(
            db.verify_iroh_token("tok-secret-a").unwrap().as_deref(),
            Some("wt-a")
        );
        assert_eq!(
            db.verify_iroh_token("tok-secret-b").unwrap().as_deref(),
            Some("wt-b")
        );
        // A forged / unknown token resolves to nothing.
        assert_eq!(db.verify_iroh_token("nope").unwrap(), None);

        // Revoked tokens no longer verify.
        db.revoke_iroh_token("wt-a").unwrap();
        assert_eq!(db.verify_iroh_token("tok-secret-a").unwrap(), None);
        assert_eq!(
            db.verify_iroh_token("tok-secret-b").unwrap().as_deref(),
            Some("wt-b")
        );
    }

    #[test]
    fn re_minting_replaces_the_token() {
        let db = Db::open_memory().unwrap();
        db.mint_iroh_token("wt", "old", 1).unwrap();
        db.mint_iroh_token("wt", "new", 2).unwrap();
        // The old token is gone; only the newest is valid.
        assert_eq!(db.verify_iroh_token("old").unwrap(), None);
        assert_eq!(db.verify_iroh_token("new").unwrap().as_deref(), Some("wt"));
    }

    #[test]
    fn migration_is_idempotent() {
        // Opening twice (re-running migrations) must not error.
        let db = Db::open_memory().unwrap();
        crate::db_iroh::migrate_v38(db.conn()).expect("re-migrate");
        db.mint_iroh_token("wt", "t", 1).unwrap();
        assert_eq!(db.verify_iroh_token("t").unwrap().as_deref(), Some("wt"));
    }
}
